title: Project Summary Webpage
description: This pages presents the summary of projects done by Amir Akbarnejad during his PhD (started Sept. 2019) in university of Alberta, under supervision of Prof. Nilanjan Ray and Dr. Gilbger Bigras.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
