title: Project Summary Webpage
description: This pages presents the summary of projects done by Amir Akbarnejad during his PhD (starting fall 2019) in university of Alberta.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
