title: Project Summary, Amir Akbarnejad
description: This pages presents the summary of projects done by Amir Akbarnejad during his PhD in university of Alberta.
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
